### ISSUE TITLE
能否实现到事件当日再进日志。

### ISSUE THREAD

**Issue by pencilboxshotmail** [luckykellan/logseq-plugin-ticktick#11]
现在用dealine创建事件时间，会从创建之日起每天出现在当日日志里。
不知道是否能用schedule创建事件时间，并在事件当日再出现在日志里。
或者能选择出现的时间段，比如提前三天提醒，然后连续三天出现在日志里。
![image](https://github.com/luckykellan/logseq-plugin-ticktick/assets/111672485/184c72cd-b990-41e9-ae84-05b291ad7c23)

**Comment by luckykellan** [comment]
久等，这里我也研究了一阵，是这样的
日志页脚中SCHEDULED AND DEADLINE默认是显示未来七天的任务，这是logseq的设定。如果只想显示当天的，那么需要在logseq的config.edn文件中加入`{:scheduled/future-days 0}`设置。
希望可以帮助到你

**Comment by pencilboxshotmail** [comment]
nice, 3q
