### ISSUE TITLE
Respect journal page name format

### ISSUE THREAD

**Issue by LoricAndre** [luckykellan/logseq-plugin-ticktick#3]
My tasks appear to be syncing properly, however the tasks from ticktick go to pages named `2024-04-Sa 6666` for instance, while my journal block is named `2024-04-13 Saturday`.
I'm using `yyyy-MM-dd EEEE` as my preferred date format.

**Comment by luckykellan** [comment]
This issue has been fixed in version 1.1.0, and we now ensure compatibility with all preferred date formats in Logseq. Your tasks should now sync correctly to the designated journal pages.
