### ISSUE TITLE
Sync function seems not work

### ISSUE THREAD

**Issue by raiots** [luckykellan/logseq-plugin-ticktick#5]
First of all, I would like to express my sincere gratitude for your hard work and dedication to this project.

When I configured this plugin and started using it, I found that it does not sync with Ticktick or push my Todo to Ticktick.

After opening the development console and disabling the other plugins, I noticed that every time I enabled this Ticktick plugin, there was an error message displayed, as shown below. Additionally, I did not find any network requests to Ticktick in the network tab.

![image](https://github.com/luckykellan/logseq-plugin-ticktick/assets/60507671/f471ac03-8c27-4aee-91e1-93705c9882b1)

Here is my config of this plugin.

![image](https://github.com/luckykellan/logseq-plugin-ticktick/assets/60507671/2b0b0915-6b5f-49c1-abbe-452cf8ff1fea)

Thank you again for your dedication and support.

**Comment by luckykellan** [comment]
It appears that the issue might have been related to the syncKeybinding not being configured. I have addressed this in the latest update, version 1.2.1, which is now available for download. Please update to this version when you can.

Alternatively, you could try manually setting the sync shortcut key to see if that helps in the meantime.

**Comment by raiots** [comment]
It works lol, thanks a lot!
