### ISSUE TITLE
求助，按照方法设置后同步失败

### ISSUE THREAD

**Issue by pencilboxshotmail** [luckykellan/logseq-plugin-ticktick#6]
按照说明设置后，logseq在重启时显示“正在同步滴答清单”，但是滴答清单无同步。
logseq在块中设置todo并回车后，无任何反应，滴答清单刷新后也没有反应。
求帮助~

**Comment by luckykellan** [comment]
抱歉久等，麻烦提供两张截图，一张是该插件的设置页面的（token打码），一张是开发者工具的控制台截图，上面有报错信息

**Comment by pencilboxshotmail** [comment]
> 抱歉久等，麻烦提供两张截图，一张是该插件的设置页面的（token打码），一张是开发者工具的控制台截图，上面有报错信息

没关系。感谢回复。请问开发者工具的控制台如何进入？我是小白~

另外，好像网络问题，我图片上传失败，等我换个网络看看。

**Comment by Calibburn** [comment]
遇到了同样的问题，请问开发者工具控制台如何打开？

**Comment by luckykellan** [comment]
win: ctrl+shift+I
mac: command+option+I

**Comment by Calibburn** [comment]
![微信截图_20240506143706](https://github.com/luckykellan/logseq-plugin-ticktick/assets/76148652/7fb7dc1e-6b71-49a4-b335-c981d1acbb4c)
![微信截图_20240506143540](https://github.com/luckykellan/logseq-plugin-ticktick/assets/76148652/51a99e1a-f991-490b-b74b-c24aa22e58f2)

**Comment by pencilboxshotmail** [comment]
![插件截图](https://github.com/luckykellan/logseq-plugin-ticktick/assets/111672485/b727bee2-c545-4852-a6e6-6ef9bc49d75c)
![控制台](https://github.com/luckykellan/logseq-plugin-ticktick/assets/111672485/b3dd0cdf-1841-4ce4-b3c4-30b245a2ec10)
@luckykellan

**Comment by luckykellan** [comment]
抱歉两位，久等。
麻烦更新到1.2.2版本，再次尝试

**Comment by pencilboxshotmail** [comment]
> 抱歉两位，久等。 麻烦更新到1.2.2版本，再次尝试

成功。感谢！！！
