### ISSUE TITLE
关于Token

### ISSUE THREAD

**Issue by 0w0miki** [luckykellan/logseq-plugin-ticktick#7]
Token到期后会有提示吗？按照目前的设计还需要用户重新去拿一次token。

滴答/Ticktick有[开放API](https://developer.dida365.com/docs#/openapi)，可以用OAuth2方式获取token，可能在用户引导上更加方便。不过我试了下不能用于v2的API，只能用于v1。

不知道是否有计划未来添加习惯的同步？如果有的话，习惯只有v2的API，就只能用现在的设计。

**Comment by luckykellan** [comment]
感谢提醒，Token到期后确实没有提示，因为除了在网页端退出登录，我还没有遇到Token到期的情况，如果你遇到了Token到期可以反馈给我。
习惯的同步暂时不考虑，因为这个插件只是将滴答清单集成到Logseq的TODO体系中，目前看TODO很难提供习惯的记录，我不想因为引入这个插件造成logseq TODO功能的变更。当然，如果有更好的建议可以随时告诉我，感谢
