### ISSUE TITLE
优先级无法成功映射，请教一下为什么？

### ISSUE THREAD

**Issue by edwluo** [luckykellan/logseq-plugin-ticktick#9]
优先级无法成功映射，请教一下为什么？
<img width="142" alt="image" src="https://github.com/luckykellan/logseq-plugin-ticktick/assets/53964601/8b817ef5-807b-4992-93e1-f1c11b462278">
<img width="195" alt="image" src="https://github.com/luckykellan/logseq-plugin-ticktick/assets/53964601/e121e052-21e0-444b-8ac3-efc97f0bae0d">

**Comment by luckykellan** [comment]
版本1.2.2已解决
抱歉这么久才修复

**Comment by edwluo** [comment]
不好意思，我更新之后似乎还是跟之前一样的问题，我没有动过设置，不知道是不是应用语言问题导致的？

**Comment by luckykellan** [comment]
我仔细看了一下你发的截图，可以再这样试试吗：Now #A CECECE
去掉了标签外层的[]

**Comment by edwluo** [comment]
这样是可以的，但是 logseq 的默认 TODO 语法中，如果要用它原生语法的话，是用 [#A] 这样的，否则原生语法的特性好像就用不到了。🙂‍↔️

**Comment by luckykellan** [comment]
不好意思，你说的原生语法指什么？

**Comment by edwluo** [comment]
<img width="425" alt="image" src="https://github.com/luckykellan/logseq-plugin-ticktick/assets/53964601/f7c723d2-6af3-48b7-bbf1-476f27c1f83b">
<img width="80" alt="image" src="https://github.com/luckykellan/logseq-plugin-ticktick/assets/53964601/42fac808-a1ea-41ff-a6cc-85ffc1c7a746">
就是 logseq 的默认优先级 最高优先级的语法应该是  [#A] 而不是单纯的 #A？

**Comment by luckykellan** [comment]
我明白了，因为我平时确实没有这么用过，感谢。
明天会更新一个版本来支持
